apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-account
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-account
  template:
    metadata:
      labels:
        app: ms-account
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: ms-account
          image: <aws_account_id>.dkr.ecr.<region>.amazonaws.com/ms-account:latest
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-db1:5432/rad_db-data
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ms-secrets
                  key: POSTGRES_PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: org.hibernate.dialect.PostgreSQLDialect
          ports:
            - containerPort: 8085
---
apiVersion: v1
kind: Service
metadata:
  name: ms-account
spec:
  selector:
    app: ms-account
  ports:
    - port: 8085
      targetPort: 8085
  type: ClusterIP
