apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-covid
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-covid
  template:
    metadata:
      labels:
        app: ms-covid
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: ms-covid
          image: 047719649687.dkr.ecr.us-east-2.amazonaws.com/micro:ms-covid
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SPRING_DATA_MONGODB_URI
              value: mongodb://mongo:27017/coviddb
            - name: RAPIDAPI_KEY
              valueFrom:
                secretKeyRef:
                  name: ms-secrets
                  key: RAPIDAPI_KEY
          ports:
            - containerPort: 8084
---
apiVersion: v1
kind: Service
metadata:
  name: ms-covid
spec:
  selector:
    app: ms-covid
  ports:
    - port: 8084
      targetPort: 8084
  type: ClusterIP
