apiVersion: apps/v1
kind: Deployment
metadata:
  name: ms-store
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ms-store
  template:
    metadata:
      labels:
        app: ms-store
    spec:
      imagePullSecrets:
        - name: ecr-secret
      containers:
        - name: ms-store
          image: 047719649687.dkr.ecr.us-east-2.amazonaws.com/micro:ms-store
          env:
            - name: SPRING_PROFILES_ACTIVE
              value: docker
            - name: SPRING_DATASOURCE_URL
              value: jdbc:postgresql://postgres-db2:5432/rad_store_db
            - name: SPRING_DATASOURCE_USERNAME
              value: postgres
            - name: SPRING_DATASOURCE_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: ms-secrets
                  key: POSTGRES_PASSWORD
            - name: SPRING_JPA_HIBERNATE_DDL_AUTO
              value: update
            - name: SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT
              value: org.hibernate.dialect.PostgreSQLDialect
          ports:
            - containerPort: 8086
---
apiVersion: v1
kind: Service
metadata:
  name: ms-store
spec:
  selector:
    app: ms-store
  ports:
    - port: 8086
      targetPort: 8086
  type: ClusterIP
