apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db1
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db1
  template:
    metadata:
      labels:
        app: postgres-db1
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: rad_db-data
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: admin
          # No volumeMounts needed if you're using ephemeral storage
          volumeMounts:
            - name: postgres-db1-data
              mountPath: /var/lib/postgresql/data
      # Remove the persistent volume claim (PVC) part
      volumes:
        - name: postgres-db1-data
          emptyDir: {}  # Use ephemeral storage (emptyDir)
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db1
spec:
  selector:
    app: postgres-db1
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
