apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres-db2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres-db2
  template:
    metadata:
      labels:
        app: postgres-db2
    spec:
      containers:
        - name: postgres
          image: postgres:latest
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: rad_store_db
            - name: POSTGRES_USER
              value: postgres
            - name: POSTGRES_PASSWORD
              value: admin
          volumeMounts:
            - name: postgres-db2-data
              mountPath: /var/lib/postgresql/data
---
apiVersion: v1
kind: Service
metadata:
  name: postgres-db2
spec:
  selector:
    app: postgres-db2
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-db2-data
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
