version: '3.8'
services:
  mongo:
    image: mongo:4.4
    container_name: mongo
    ports:
      - 27017:27017
    volumes:
      - ./mongo-data:/data/db

  # PostgreSQL for Database 1
  postgres-db1:
    image: postgres:latest
    container_name: postgres-rad_db-data
    ports:
      - "5432:5432"  # Maps host port 5434 to container's default port 5432
    environment:
      POSTGRES_DB: rad_db-data
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - ./postgres-rad_db-data_new:/var/lib/postgresql/data

  # PostgreSQL for Database 2
  postgres-db2:
    image: postgres:latest
    container_name: postgres-rad_store_db-data_new
    ports:
      - "5434:5432"
    environment:
      POSTGRES_DB: rad_store_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
    volumes:
      - ./postgres-rad_store_db-data_new:/var/lib/postgresql/data

  ## Eureka Server
  service-discovery:
    image: shavitc/ms_service_discovery:latest
    container_name: service-discovery
    pull_policy: always
    ports:
      - "8761:8761"
    environment:
      - SPRING_PROFILES_ACTIVE=docker

  api-gateway:
    image: shavitc/ms_api_gateway:latest
    container_name: api-gateway
    pull_policy: always
    ports:
      - "8080:8080"
    expose:
      - "8080"
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - LOGGING_LEVEL_ORG_SPRINGFRAMEWORK_SECURITY= TRACE
    depends_on:
      - service-discovery

  ms-news:
    container_name: ms-news
    image: shavitc/ms-news:latest
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/newsdb
      - NEWSAPI_KEY=${NEWSAPI_KEY}
    depends_on:
      - mongo
      - service-discovery
      - api-gateway

  ms-covid:
    container_name: ms-covid
    image: shavitc/ms-covid:latest
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATA_MONGODB_URI=mongodb://mongo:27017/coviddb
      - RAPIDAPI_KEY=${RAPIDAPI_KEY}
    depends_on:
      - mongo
      - service-discovery
      - api-gateway

  ms-account:
    container_name: ms-account
    image: shavitc/ms-account:latest
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db1:5432/rad_db-data
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - postgres-db1
      - service-discovery
      - api-gateway

  ms-store:
    container_name: ms-store
    image: shavitc/ms-store:latest
    pull_policy: always
    environment:
      - SPRING_PROFILES_ACTIVE=docker
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-db2:5432/rad_store_db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=admin
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
      - SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT=org.hibernate.dialect.PostgreSQLDialect
    depends_on:
      - postgres-db2
      - service-discovery
      - api-gateway

